---

- name: Configure SSH principals
  when: _sshd.principals is defined
  block:
    - name: Create Authorized Principals Files
      ansible.builtin.template:
        src: "etc/ssh/authorized_principals.j2"
        dest: "/etc/ssh/{{ item.key }}_principals"
        owner: "root"
        group: "root"
        mode: "0644"
      with_dict: "{{ _sshd.principals.mappings }}"

    - name: Update sshd configuration - Authorized Principals
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^AuthorizedPrincipalsFile.*$'
        line: "AuthorizedPrincipalsFile /etc/ssh/{{ _sshd.principals.filename_pattern }}"

- name: Configure SSH KRL
  when: _sshd.krl is defined
  block:
    # This is done so we can be sure the file exists. If it
    # does not, SSHD will start, but reject any public key basic
    # logins, effectively locking us out.
    - name: Ensure KRL file exists
      ansible.builtin.file:
        name: "{{ _sshd.krl.filename }}"
        owner: root
        group: root
        mode: 0644
        state: touch
        access_time: preserve
        modification_time: preserve

    - name: Update sshd configuration - Revoked Keys
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^RevokedKeys.*$'
        line: "RevokedKeys {{ _sshd.krl.filename }}"

    # skip idempotence tests
    - name: Run initial KRL update # noqa no-changed-when
      ansible.builtin.command: "{{ _sshd.krl.update_command }} {{ _sshd.krl.s3_key }} {{ _sshd.krl.filename }}"
      tags: molecule-idempotence-notest

    - name: Install KRL update cronjob # noqa args[module]
      ansible.builtin.cron:
        name: "Update SSH Revoked Keys"
        job: "{{ _sshd.krl.update_command }} {{ _sshd.krl.s3_key }} {{ _sshd.krl.filename }}"
        special_time: "{{ _sshd.krl.cron_special_time | default('hourly') }}"

- name: Start ssh service
  ansible.builtin.systemd:
    name: ssh
    state: started
