---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update APT Cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      register: result
      until: result is succeeded
      when: ansible_os_family == 'Debian'

    - name: Install openssh-server
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - openssh-server

    # https://github.com/microsoft/WSL/issues/3621
    - name: Create /run/sshd inside containers
      ansible.builtin.file:
        path: /run/sshd
        state: directory
        mode: "0755"
        owner: root
      when: ansible_virtualization_type in ['docker', 'podman', 'lxc', 'containerd', 'VirtualPC']
  tasks:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
